### ISSUE TITLE
bug: checkov errors out on dependencies?

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/terraform-modules-vmseries-ci-workflows#17]
```
[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.
[INFO] Initializing environment for https://github.com/bridgecrewio/checkov.git.
[INFO] Installing environment for https://github.com/bridgecrewio/checkov.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Checkov..................................................................Failed
- hook id: checkov
- duration: 0.32s
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/lib/python3.10/site-packages/checkov/main.py", line [20](https://github.com/PaloAltoNetworks/vm-series-gh-actions/actions/runs/4184962868/jobs/7251366362#step:8:21), in <module>
    from checkov.argo_workflows.runner import Runner as argo_workflows_runner
  File "/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/lib/python3.10/site-packages/checkov/argo_workflows/runner.py", line 8, in <module>
    from checkov.common.output.report import CheckType
  File "/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/lib/python3.10/site-packages/checkov/common/output/report.py", line [21](https://github.com/PaloAltoNetworks/vm-series-gh-actions/actions/runs/4184962868/jobs/7251366362#step:8:22), in <module>
    from checkov.common.util.json_utils import CustomJSONEncoder
  File "/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/lib/python3.10/site-packages/checkov/common/util/json_utils.py", line 6, in <module>
    from packaging.version import LegacyVersion, Version
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/runner/.cache/pre-commit/repor3gr5pl7/py_env-python3/lib/python3.10/site-packages/packaging/version.py)

Error: Process completed with exit code 1.
```

**Comment by FoSix** [comment]
fixed with #14
